# Generated by Django 4.0 on 2023-02-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_profile_is_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=100)),
                ('seats', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=100)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
