# Generated by Django 4.0 on 2023-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='companyName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
