# Generated by Django 4.0 on 2023-02-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ads_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='company',
            new_name='companyname',
        ),
    ]
