# Generated by Django 4.0 on 2023-02-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_remove_ads_companyname_ads_companylink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='companyLink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
