# Generated by Django 4.0 on 2023-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
    ]
